apiVersion: v1
kind: Service
metadata:
  name: geo-service
  labels:
    app: geo-service
spec:
  type: ClusterIP
  selector:
    app: geo-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50004
