apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-service
  labels:
    app: geo-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geo-service
      tier: backend
  template:
    metadata:
      labels:
        app: geo-service
        tier: backend
    spec:
      containers:
        - name: geo-service
          image: "geo-service:0.1"
          ports:
            - containerPort: 50004
          env:
            - name: port
              valueFrom:
                configMapKeyRef:
                  name: geo-service-config
                  key: port
