apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
      tier: backend
  template:
    metadata:
      labels:
        app: auth-service
        tier: backend
    spec:
      containers:
        - name: auth-service
          image: "auth-service:1.0.0"
          ports:
            - containerPort: 50051
          env:
            - name: port
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: port
